- name: install everything
  apt:
    pkg:
    - fzf
    - zsh
    - direnv
  become: yes


- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: ~/.oh-my-zsh
    clone: yes
    update: yes
    depth: 1

- name: Clone oh-my-zsh/plugins/zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: yes
    update: yes
    depth: 1

- name: Clone oh-my-zsh/plugins/zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes
    update: yes
    depth: 1

- name: Clone oh-my-zsh/themes/powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    clone: yes
    update: yes
    depth: 1

- name: Copy .zshrc
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc
    force: yes

- name: Copy .bashrc
  copy:
    src: ~/.bashrc
    dest: ~/.bashrc
    force: yes

- name: Copy .p10k.zsh
  copy:
    src: ~/.p10k.zsh
    dest: ~/.p10k.zsh
    force: yes
